import type { Agent, Channel, NavItem, SkillMeta } from "./types";

export const AGENTS: Agent[] = [
  {
    id: "honeybadger",
    name: "HoneyBadger Orchestrator",
    emoji: "🦡",
    color: "#f59e0b",
    isDefault: true,
    role: "Primary orchestrator and Captain-facing assistant",
    model: "google/gemini-3-flash-preview",
    fallbacks: ["google/gemini-2.5-flash"],
    skills: [
      "memory-operations",
      "systems-planning",
      "ops-diagnostics",
      "creative-strategy",
      "execution-governance",
      "observability",
    ],
    allowAgents: [
      "knowledge-management",
      "ops-coordinator",
      "quality-gate",
      "strategic-horizon-systems",
      "operational-diagnostics-optimization",
      "creative-director",
      "creative-strategist",
      "execution-governor",
      "architect",
      "researcher",
      "deal-closer",
      "market-advisory",
    ],
    maxConcurrent: 4,
    maxSpawnDepth: 2,
  },
  {
    id: "knowledge-management",
    name: "Knowledge Management Agent",
    emoji: "🧠",
    color: "#22c55e",
    isDefault: false,
    role: "Memory continuity, recall packs, and writeback deltas",
    model: "google/gemini-2.5-flash",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["memory-operations", "observability"],
    allowAgents: [],
  },
  {
    id: "strategic-horizon-systems",
    name: "Strategic Horizon and Systems Agent",
    emoji: "🧭",
    color: "#6366f1",
    isDefault: false,
    role: "Long-horizon planning and dependency scenario design",
    model: "google/gemini-2.5-pro",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["systems-planning", "observability"],
    allowAgents: [],
  },
  {
    id: "operational-diagnostics-optimization",
    name: "Operational Diagnostics and Optimization Agent",
    emoji: "🛠️",
    color: "#14b8a6",
    isDefault: false,
    role: "Root-cause diagnostics, reliability, and optimization checks",
    model: "google/gemini-2.5-flash",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["ops-diagnostics", "observability"],
    allowAgents: [],
  },
  {
    id: "creative-director",
    name: "Creative Director Agent",
    emoji: "🎨",
    color: "#a855f7",
    isDefault: false,
    role: "Narrative systems, concept direction, and creative options",
    model: "google/gemini-2.5-pro",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["creative-direction", "creative-strategy"],
    allowAgents: [],
  },
  {
    id: "creative-strategist",
    name: "Creative Strategist Agent",
    emoji: "🧩",
    color: "#ec4899",
    isDefault: false,
    role: "Campaign strategy and concept-to-execution planning",
    model: "google/gemini-2.5-pro",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["creative-strategy", "systems-planning"],
    allowAgents: [],
  },
  {
    id: "execution-governor",
    name: "Execution Governor Agent",
    emoji: "🧱",
    color: "#f43f5e",
    isDefault: false,
    role: "Go/no-go gating, dependency checks, and execution governance",
    model: "google/gemini-2.5-flash",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["execution-governance", "ops-diagnostics"],
    allowAgents: [],
  },
  {
    id: "ops-coordinator",
    name: "Ops Coordinator",
    emoji: "⚙️",
    color: "#3b82f6",
    isDefault: false,
    role: "Operations routing support and queue sequencing",
    model: "google/gemini-3-flash-preview",
    fallbacks: ["google/gemini-2.5-flash"],
    skills: ["ops-diagnostics", "observability"],
    allowAgents: [],
  },
  {
    id: "quality-gate",
    name: "Quality Gate",
    emoji: "🔍",
    color: "#10b981",
    isDefault: false,
    role: "Schema and quality validation support",
    model: "google/gemini-3-flash-preview",
    fallbacks: ["google/gemini-2.5-flash"],
    skills: ["config-secrets-audit", "execution-governance"],
    allowAgents: [],
  },
  {
    id: "architect",
    name: "Architect",
    emoji: "🏗️",
    color: "#8b5cf6",
    isDefault: false,
    role: "System-level design + reliability",
    model: "google/gemini-2.5-pro",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["systems-planning", "config-secrets-audit"],
    allowAgents: [],
  },
  {
    id: "researcher",
    name: "Researcher",
    emoji: "🔬",
    color: "#06b6d4",
    isDefault: false,
    role: "Discovery + workflow packaging",
    model: "google/gemini-2.5-pro",
    fallbacks: ["google/gemini-3-flash-preview"],
    skills: ["research-discovery", "observability"],
    allowAgents: [],
  },
  {
    id: "deal-closer",
    name: "Deal Closer",
    emoji: "🤝",
    color: "#ef4444",
    isDefault: false,
    role: "Outcome-oriented advisory output",
    model: "google/gemini-2.5-flash",
    fallbacks: ["google/gemini-2.5-flash"],
    skills: ["business-advisory", "research-discovery"],
    allowAgents: [],
  },
  {
    id: "market-advisory",
    name: "Market Advisory",
    emoji: "📈",
    color: "#f97316",
    isDefault: false,
    role: "Market analysis/advisory output",
    model: "openai/gpt-4o-mini",
    fallbacks: ["google/gemini-2.5-flash"],
    skills: ["market-intelligence", "research-discovery"],
    allowAgents: [],
  },
];

export const SKILL_META: SkillMeta = {
  "memory-operations": { color: "#22c55e", desc: "Memory capture, retrieval, and continuity" },
  "systems-planning": { color: "#6366f1", desc: "Scenario planning and dependency design" },
  "ops-diagnostics": { color: "#14b8a6", desc: "Root-cause diagnostics and optimization" },
  "creative-direction": { color: "#a855f7", desc: "Narrative systems and concept direction" },
  "creative-strategy": { color: "#ec4899", desc: "Campaign strategy and positioning options" },
  "execution-governance": { color: "#f43f5e", desc: "Go/no-go gates and execution controls" },
  "research-discovery": { color: "#06b6d4", desc: "Evidence gathering and option analysis" },
  "business-advisory": { color: "#ef4444", desc: "Actionable business framing and plans" },
  "market-intelligence": { color: "#f97316", desc: "Market signals, trends, and risk framing" },
  "config-secrets-audit": { color: "#10b981", desc: "Config validation & secrets scanning" },
  observability: { color: "#8b5cf6", desc: "Logging, metrics & system monitoring" },
};

export const CHANNELS: Channel[] = [
  {
    id: "telegram",
    name: "Telegram",
    emoji: "✈️",
    color: "#06b6d4",
    desc: "Telegram bot channel",
    policy: { dm: "allowlist", group: "allowlist", mention: "required" },
  },
  {
    id: "discord",
    name: "Discord",
    emoji: "🎮",
    color: "#5865f2",
    desc: "Discord bot channel",
    policy: null,
  },
  {
    id: "slack",
    name: "Slack",
    emoji: "💬",
    color: "#e01e5a",
    desc: "Slack workspace channel",
    policy: null,
  },
  {
    id: "webchat",
    name: "WebChat",
    emoji: "🌐",
    color: "#10b981",
    desc: "Browser web chat UI",
    policy: null,
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    emoji: "📱",
    color: "#25d366",
    desc: "WhatsApp messaging",
    policy: null,
  },
  {
    id: "signal",
    name: "Signal",
    emoji: "🔐",
    color: "#3a76f0",
    desc: "Signal private messaging",
    policy: null,
  },
];

export const NAV_ITEMS: NavItem[] = [
  { id: "overview", icon: "⬡", label: "Overview" },
  { id: "agents", icon: "🦡", label: "Agents" },
  { id: "chat", icon: "💬", label: "Chat" },
  { id: "sessions", icon: "📋", label: "Sessions" },
  { id: "subagents", icon: "⚡", label: "Subagents" },
  { id: "skills", icon: "🔧", label: "Skills" },
  { id: "channels", icon: "📡", label: "Channels" },
  { id: "config", icon: "⚙️", label: "Config" },
];
