import type { AuditReport, AuditSnippet } from "../types.js";

/** Converts an AuditReport into a full markdown report string. */
export function formatFullReport(report: AuditReport): string {
  const lines: string[] = [];

  lines.push(`# Company Audit Report: ${report.company.name}`);
  lines.push(`**Date:** ${new Date(report.ts).toLocaleDateString("en-US", { dateStyle: "long" })}`);
  lines.push(
    `**Industry:** ${report.company.industry} | **Stage:** ${report.company.stage} | **Team Size:** ${report.company.teamSize}`,
  );
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## Overall Score: ${report.compositeScore}/100 — Grade: ${report.compositeGrade}`);
  lines.push(``);

  // Dimension summary table
  lines.push(`| Dimension | Score | Grade | Critical | Warn |`);
  lines.push(`|---|---|---|---|---|`);
  for (const d of report.dimensions) {
    const crit = d.findings.filter((f) => f.severity === "critical").length;
    const warn = d.findings.filter((f) => f.severity === "warn").length;
    lines.push(
      `| ${d.dimension.charAt(0).toUpperCase() + d.dimension.slice(1)} | ${d.score}/100 | ${d.grade} | ${crit} | ${warn} |`,
    );
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Findings by dimension
  for (const d of report.dimensions) {
    if (d.findings.length === 0) {
      continue;
    }
    lines.push(`## ${d.dimension.charAt(0).toUpperCase() + d.dimension.slice(1)}`);
    for (const f of d.findings) {
      const emoji = f.severity === "critical" ? "🔴" : f.severity === "warn" ? "🟡" : "🔵";
      lines.push(`### ${emoji} ${f.title}`);
      lines.push(f.detail);
      if (f.remediation) {
        lines.push(`**Fix:** ${f.remediation}`);
      }
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`*Report generated by X AuditIQ — powered by the AI Council Conductor methodology.*`);

  return lines.join("\n");
}

/** Creates a trimmed free-hook snippet from an AuditReport. */
export function formatSnippet(report: AuditReport): AuditSnippet {
  return {
    company: report.company.name,
    compositeGrade: report.compositeGrade,
    topFindings: report.topFindings.slice(0, 3).map((f) => ({
      title: f.title,
      severity: f.severity,
      detail: f.detail,
    })),
    teaser:
      `${report.company.name} scored ${report.compositeScore}/100 in the X AuditIQ diagnostic. ` +
      `We identified ${report.summary.critical} critical issue(s) and ${report.summary.warn} warning(s) ` +
      `across your business. The full report includes prioritized remediation steps for each finding. ` +
      `Reply to this message to get your full audit.`,
  };
}
